# k8s/grpc-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nsg-data-importer
  labels:
    app: nsg-data-importer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nsg-data-importer
  template:
    metadata:
      labels:
        app: nsg-data-importer
    spec:
      containers:
      - name: grpc-server
        image: dchidambaram/nsg-data-importer:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 50051
          name: grpc
        livenessProbe:
          tcpSocket:
            port: grpc
          initialDelaySeconds: 15
          periodSeconds: 20
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: grpc
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3