# k8s/grpc-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nsg-data-importer
  namespace: default
  labels:
    app: nsg-data-importer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nsg-data-importer
  template:
    metadata:
      labels:
        app: nsg-data-importer
    spec:
      volumes:
      - name: nsg-kakfa-secret-volume
        secret:
          secretName: nsg-kafka-secrets
      containers:
      - name: nsg-data-importer
        image: dchidambaram/nsg-data-importer:latest
        imagePullPolicy: Always
        volumeMounts:
          - name: nsg-kakfa-secret-volume
            mountPath: "/etc/secrets"
            readOnly: true
        ports:
        - containerPort: 50051
          name: grpc
        livenessProbe:
          tcpSocket:
            port: grpc
          initialDelaySeconds: 15
          periodSeconds: 20
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: grpc
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3